<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <AssemblyName>viwik.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>viwik.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <Version>1.0.4</Version>
    <Authors>vi-wik</Authors>
    <Description>粤语学习数据访问层</Description>
    <PackageProjectUrl>https://github.com/vi-wik/CantoneseLearning</PackageProjectUrl>
    <RepositoryUrl>https://github.com/vi-wik/CantoneseLearning</RepositoryUrl>
    <AssemblyVersion>1.0.4</AssemblyVersion>
    <FileVersion>1.0.4</FileVersion>
    <PackageId>$(AssemblyName)</PackageId>
    <PackageReleaseNotes>命名空间更正</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.9" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CantoneseLearning.Data\CantoneseLearning.Data.csproj" />
    <ProjectReference Include="..\CantoneseLearning.Model\CantoneseLearning.Model.csproj" />
    <ProjectReference Include="..\CantoneseLearning.Utility\CantoneseLearning.Utility.csproj" />
  </ItemGroup>

</Project>
